#!/bin/sh

if [ "$1" = "configure" ]; then
    cf="/etc/default/hostapd"
    dpkg-divert --add --package patchbox-wifi --rename --divert ${cf}.distrib ${cf}
    [ \! -e ${cf} -o -L ${cf} ] && ln -sf ${cf}.patchbox ${cf}
fi

systemctl daemon-reload

# Check if we're being upgraded on MODEP image.
if [ -e "/usr/lib/systemd/system/pisound-hotspot.service" ]; then
	sed -i 's/Pisound/MODEP/g' /etc/hostapd/hostapd.conf
	if $(systemctl is-enabled -q pisound-hotspot); then
		systemctl disable pisound-hotspot
		systemctl stop pisound-hotspot
		systemctl enable wifi-hotspot
		systemctl start wifi-hotspot
	fi
	rm -f /usr/lib/systemd/system/pisound-hotspot.service
	systemctl daemon-reload
else
	if $(systemctl is-enabled -q wifi-hotspot); then
		systemctl restart wifi-hotspot
	fi
fi
