#!/bin/sh

install_repo() {
	if [ ! -d "$3" ]; then
		echo "Cloning $1 repository from $2..."
		git clone "$2" "$3"
	else
		echo "Updating $1 repository with latest stuff in $2..."
		cd $3 && git -c user.name="apt-get" -c user.email="apt@get" stash && git pull --no-rebase
	fi
}

install_repo patchbox-modules https://github.com/BlokasLabs/patchbox-modules /usr/local/patchbox-modules

# Delete /etc/motd created by previous versions - the file was moved to 'patchbox' package.
if echo 56a51c4b2bc0a1a50a8afb785ebe335ece7bae2281093c36920a3e09c51c9fdd /etc/motd | sha256sum -c --status --quiet > /dev/null 2>&1; then
	rm /etc/motd
fi

#DEBHELPER#
